from __future__ import annotations

from math import isclose, log, sqrt
from pathlib import Path

import pandas as pd

from trial_transportability_atlas.effect_candidates import build_effect_candidates
from trial_transportability_atlas.effect_derivation import (
    build_signed_effect_estimates,
    materialize_signed_effect_outputs,
)
from trial_transportability_atlas.topics import PHASE1_TOPIC


def build_outcomes_fixture() -> pd.DataFrame:
    return pd.DataFrame(
        [
            {
                "nct_id": "N1",
                "source_table": "outcome_measurements",
                "record_type": "measurement",
                "outcome_id": "1",
                "outcome_type": "PRIMARY",
                "outcome_name": "Erectile Function Score",
                "analysis_population": "All participants with a valid assessment",
                "time_frame": "Week 12",
                "unit": "score",
                "result_group_id": "10",
                "ctgov_group_code": "OG000",
                "classification": None,
                "category": None,
                "param_type": "LEAST_SQUARES_MEAN",
                "value_text": "15.1",
                "value_num": 15.1,
                "dispersion_type": "Standard Error",
                "dispersion_value": 2.15,
                "event_type": None,
                "subjects_affected": None,
                "subjects_at_risk": None,
                "event_count": None,
                "organ_system": None,
                "adverse_event_term": None,
                "provenance": "x",
            },
            {
                "nct_id": "N1",
                "source_table": "outcome_measurements",
                "record_type": "measurement",
                "outcome_id": "1",
                "outcome_type": "PRIMARY",
                "outcome_name": "Erectile Function Score",
                "analysis_population": "All participants with a valid assessment",
                "time_frame": "Week 12",
                "unit": "score",
                "result_group_id": "11",
                "ctgov_group_code": "OG001",
                "classification": None,
                "category": None,
                "param_type": "LEAST_SQUARES_MEAN",
                "value_text": "12.2",
                "value_num": 12.2,
                "dispersion_type": "Standard Error",
                "dispersion_value": 2.0,
                "event_type": None,
                "subjects_affected": None,
                "subjects_at_risk": None,
                "event_count": None,
                "organ_system": None,
                "adverse_event_term": None,
                "provenance": "x",
            },
            {
                "nct_id": "N2",
                "source_table": "outcome_measurements",
                "record_type": "measurement",
                "outcome_id": "2",
                "outcome_type": "SECONDARY",
                "outcome_name": "Sexual Activity Frequency",
                "analysis_population": "Full Analysis Set",
                "time_frame": "Baseline, Week 4, Week 12",
                "unit": "activities per week",
                "result_group_id": "20",
                "ctgov_group_code": "OG000",
                "classification": "Week 4:",
                "category": None,
                "param_type": "MEAN",
                "value_text": "-1.6",
                "value_num": -1.6,
                "dispersion_type": "Standard Deviation",
                "dispersion_value": 1.59,
                "event_type": None,
                "subjects_affected": None,
                "subjects_at_risk": None,
                "event_count": None,
                "organ_system": None,
                "adverse_event_term": None,
                "provenance": "x",
            },
            {
                "nct_id": "N2",
                "source_table": "outcome_measurements",
                "record_type": "measurement",
                "outcome_id": "2",
                "outcome_type": "SECONDARY",
                "outcome_name": "Sexual Activity Frequency",
                "analysis_population": "Full Analysis Set",
                "time_frame": "Baseline, Week 4, Week 12",
                "unit": "activities per week",
                "result_group_id": "21",
                "ctgov_group_code": "OG001",
                "classification": "Week 4:",
                "category": None,
                "param_type": "MEAN",
                "value_text": "-1.1",
                "value_num": -1.1,
                "dispersion_type": "Standard Deviation",
                "dispersion_value": 1.97,
                "event_type": None,
                "subjects_affected": None,
                "subjects_at_risk": None,
                "event_count": None,
                "organ_system": None,
                "adverse_event_term": None,
                "provenance": "x",
            },
            {
                "nct_id": "N2",
                "source_table": "outcome_measurements",
                "record_type": "measurement",
                "outcome_id": "2",
                "outcome_type": "SECONDARY",
                "outcome_name": "Sexual Activity Frequency",
                "analysis_population": "Full Analysis Set",
                "time_frame": "Baseline, Week 4, Week 12",
                "unit": "activities per week",
                "result_group_id": "20",
                "ctgov_group_code": "OG000",
                "classification": "Week 12:",
                "category": None,
                "param_type": "MEAN",
                "value_text": "-1.4",
                "value_num": -1.4,
                "dispersion_type": "Standard Deviation",
                "dispersion_value": 3.13,
                "event_type": None,
                "subjects_affected": None,
                "subjects_at_risk": None,
                "event_count": None,
                "organ_system": None,
                "adverse_event_term": None,
                "provenance": "x",
            },
            {
                "nct_id": "N2",
                "source_table": "outcome_measurements",
                "record_type": "measurement",
                "outcome_id": "2",
                "outcome_type": "SECONDARY",
                "outcome_name": "Sexual Activity Frequency",
                "analysis_population": "Full Analysis Set",
                "time_frame": "Baseline, Week 4, Week 12",
                "unit": "activities per week",
                "result_group_id": "21",
                "ctgov_group_code": "OG001",
                "classification": "Week 12:",
                "category": None,
                "param_type": "MEAN",
                "value_text": "-2.0",
                "value_num": -2.0,
                "dispersion_type": "Standard Deviation",
                "dispersion_value": 3.07,
                "event_type": None,
                "subjects_affected": None,
                "subjects_at_risk": None,
                "event_count": None,
                "organ_system": None,
                "adverse_event_term": None,
                "provenance": "x",
            },
            {
                "nct_id": "N3",
                "source_table": "outcome_measurements",
                "record_type": "measurement",
                "outcome_id": "3",
                "outcome_type": "PRIMARY",
                "outcome_name": "Walk Distance",
                "analysis_population": "The FAS population with Multiple Imputation (MI) and LOCF were considered.",
                "time_frame": "Baseline, Week 12",
                "unit": "meters",
                "result_group_id": "30",
                "ctgov_group_code": "OG000",
                "classification": "Baseline (FAS with MI)",
                "category": None,
                "param_type": "MEAN",
                "value_text": "100",
                "value_num": 100.0,
                "dispersion_type": "Standard Deviation",
                "dispersion_value": 10.0,
                "event_type": None,
                "subjects_affected": None,
                "subjects_at_risk": None,
                "event_count": None,
                "organ_system": None,
                "adverse_event_term": None,
                "provenance": "x",
            },
            {
                "nct_id": "N3",
                "source_table": "outcome_measurements",
                "record_type": "measurement",
                "outcome_id": "3",
                "outcome_type": "PRIMARY",
                "outcome_name": "Walk Distance",
                "analysis_population": "The FAS population with Multiple Imputation (MI) and LOCF were considered.",
                "time_frame": "Baseline, Week 12",
                "unit": "meters",
                "result_group_id": "31",
                "ctgov_group_code": "OG001",
                "classification": "Baseline (FAS with MI)",
                "category": None,
                "param_type": "MEAN",
                "value_text": "95",
                "value_num": 95.0,
                "dispersion_type": "Standard Deviation",
                "dispersion_value": 11.0,
                "event_type": None,
                "subjects_affected": None,
                "subjects_at_risk": None,
                "event_count": None,
                "organ_system": None,
                "adverse_event_term": None,
                "provenance": "x",
            },
            {
                "nct_id": "N3",
                "source_table": "outcome_measurements",
                "record_type": "measurement",
                "outcome_id": "3",
                "outcome_type": "PRIMARY",
                "outcome_name": "Walk Distance",
                "analysis_population": "The FAS population with Multiple Imputation (MI) and LOCF were considered.",
                "time_frame": "Baseline, Week 12",
                "unit": "meters",
                "result_group_id": "30",
                "ctgov_group_code": "OG000",
                "classification": "Change from BL at Week 12 (FAS with MI)",
                "category": None,
                "param_type": "MEAN",
                "value_text": "10",
                "value_num": 10.0,
                "dispersion_type": "Standard Deviation",
                "dispersion_value": 5.0,
                "event_type": None,
                "subjects_affected": None,
                "subjects_at_risk": None,
                "event_count": None,
                "organ_system": None,
                "adverse_event_term": None,
                "provenance": "x",
            },
            {
                "nct_id": "N3",
                "source_table": "outcome_measurements",
                "record_type": "measurement",
                "outcome_id": "3",
                "outcome_type": "PRIMARY",
                "outcome_name": "Walk Distance",
                "analysis_population": "The FAS population with Multiple Imputation (MI) and LOCF were considered.",
                "time_frame": "Baseline, Week 12",
                "unit": "meters",
                "result_group_id": "31",
                "ctgov_group_code": "OG001",
                "classification": "Change from BL at Week 12 (FAS with MI)",
                "category": None,
                "param_type": "MEAN",
                "value_text": "6",
                "value_num": 6.0,
                "dispersion_type": "Standard Deviation",
                "dispersion_value": 4.0,
                "event_type": None,
                "subjects_affected": None,
                "subjects_at_risk": None,
                "event_count": None,
                "organ_system": None,
                "adverse_event_term": None,
                "provenance": "x",
            },
            {
                "nct_id": "N4",
                "source_table": "outcome_measurements",
                "record_type": "measurement",
                "outcome_id": "4",
                "outcome_type": "SECONDARY",
                "outcome_name": "Improved Symptoms",
                "analysis_population": "Full Analysis Set",
                "time_frame": "Week 12",
                "unit": "Participants",
                "result_group_id": "40",
                "ctgov_group_code": "OG000",
                "classification": None,
                "category": "Yes",
                "param_type": "COUNT_OF_PARTICIPANTS",
                "value_text": "15",
                "value_num": 15.0,
                "dispersion_type": None,
                "dispersion_value": None,
                "event_type": None,
                "subjects_affected": None,
                "subjects_at_risk": None,
                "event_count": None,
                "organ_system": None,
                "adverse_event_term": None,
                "provenance": "x",
            },
            {
                "nct_id": "N4",
                "source_table": "outcome_measurements",
                "record_type": "measurement",
                "outcome_id": "4",
                "outcome_type": "SECONDARY",
                "outcome_name": "Improved Symptoms",
                "analysis_population": "Full Analysis Set",
                "time_frame": "Week 12",
                "unit": "Participants",
                "result_group_id": "40",
                "ctgov_group_code": "OG000",
                "classification": None,
                "category": "No",
                "param_type": "COUNT_OF_PARTICIPANTS",
                "value_text": "80",
                "value_num": 80.0,
                "dispersion_type": None,
                "dispersion_value": None,
                "event_type": None,
                "subjects_affected": None,
                "subjects_at_risk": None,
                "event_count": None,
                "organ_system": None,
                "adverse_event_term": None,
                "provenance": "x",
            },
            {
                "nct_id": "N4",
                "source_table": "outcome_measurements",
                "record_type": "measurement",
                "outcome_id": "4",
                "outcome_type": "SECONDARY",
                "outcome_name": "Improved Symptoms",
                "analysis_population": "Full Analysis Set",
                "time_frame": "Week 12",
                "unit": "Participants",
                "result_group_id": "40",
                "ctgov_group_code": "OG000",
                "classification": None,
                "category": "Missing",
                "param_type": "COUNT_OF_PARTICIPANTS",
                "value_text": "5",
                "value_num": 5.0,
                "dispersion_type": None,
                "dispersion_value": None,
                "event_type": None,
                "subjects_affected": None,
                "subjects_at_risk": None,
                "event_count": None,
                "organ_system": None,
                "adverse_event_term": None,
                "provenance": "x",
            },
            {
                "nct_id": "N4",
                "source_table": "outcome_measurements",
                "record_type": "measurement",
                "outcome_id": "4",
                "outcome_type": "SECONDARY",
                "outcome_name": "Improved Symptoms",
                "analysis_population": "Full Analysis Set",
                "time_frame": "Week 12",
                "unit": "Participants",
                "result_group_id": "41",
                "ctgov_group_code": "OG001",
                "classification": None,
                "category": "Yes",
                "param_type": "COUNT_OF_PARTICIPANTS",
                "value_text": "8",
                "value_num": 8.0,
                "dispersion_type": None,
                "dispersion_value": None,
                "event_type": None,
                "subjects_affected": None,
                "subjects_at_risk": None,
                "event_count": None,
                "organ_system": None,
                "adverse_event_term": None,
                "provenance": "x",
            },
            {
                "nct_id": "N4",
                "source_table": "outcome_measurements",
                "record_type": "measurement",
                "outcome_id": "4",
                "outcome_type": "SECONDARY",
                "outcome_name": "Improved Symptoms",
                "analysis_population": "Full Analysis Set",
                "time_frame": "Week 12",
                "unit": "Participants",
                "result_group_id": "41",
                "ctgov_group_code": "OG001",
                "classification": None,
                "category": "No",
                "param_type": "COUNT_OF_PARTICIPANTS",
                "value_text": "90",
                "value_num": 90.0,
                "dispersion_type": None,
                "dispersion_value": None,
                "event_type": None,
                "subjects_affected": None,
                "subjects_at_risk": None,
                "event_count": None,
                "organ_system": None,
                "adverse_event_term": None,
                "provenance": "x",
            },
            {
                "nct_id": "N4",
                "source_table": "outcome_measurements",
                "record_type": "measurement",
                "outcome_id": "4",
                "outcome_type": "SECONDARY",
                "outcome_name": "Improved Symptoms",
                "analysis_population": "Full Analysis Set",
                "time_frame": "Week 12",
                "unit": "Participants",
                "result_group_id": "41",
                "ctgov_group_code": "OG001",
                "classification": None,
                "category": "Missing",
                "param_type": "COUNT_OF_PARTICIPANTS",
                "value_text": "2",
                "value_num": 2.0,
                "dispersion_type": None,
                "dispersion_value": None,
                "event_type": None,
                "subjects_affected": None,
                "subjects_at_risk": None,
                "event_count": None,
                "organ_system": None,
                "adverse_event_term": None,
                "provenance": "x",
            },
            {
                "nct_id": "N5",
                "source_table": "reported_events",
                "record_type": "reported_event",
                "outcome_id": None,
                "outcome_type": None,
                "outcome_name": "Heart failure worsening",
                "analysis_population": None,
                "time_frame": "12 months",
                "unit": "participants",
                "result_group_id": "50",
                "ctgov_group_code": "EG000",
                "classification": None,
                "category": None,
                "param_type": None,
                "value_text": None,
                "value_num": None,
                "dispersion_type": None,
                "dispersion_value": None,
                "event_type": "serious",
                "subjects_affected": 2.0,
                "subjects_at_risk": 100.0,
                "event_count": None,
                "organ_system": "Cardiac disorders",
                "adverse_event_term": "Heart failure worsening",
                "provenance": "x",
            },
            {
                "nct_id": "N5",
                "source_table": "reported_events",
                "record_type": "reported_event",
                "outcome_id": None,
                "outcome_type": None,
                "outcome_name": "Heart failure worsening",
                "analysis_population": None,
                "time_frame": "12 months",
                "unit": "participants",
                "result_group_id": "51",
                "ctgov_group_code": "EG001",
                "classification": None,
                "category": None,
                "param_type": None,
                "value_text": None,
                "value_num": None,
                "dispersion_type": None,
                "dispersion_value": None,
                "event_type": "serious",
                "subjects_affected": 6.0,
                "subjects_at_risk": 100.0,
                "event_count": None,
                "organ_system": "Cardiac disorders",
                "adverse_event_term": "Heart failure worsening",
                "provenance": "x",
            },
        ]
    )


def build_arm_mapping_fixture() -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    specs = {
        "N1": (13.0, 14.0),
        "N2": (13.0, 14.0),
        "N3": (100.0, 100.0),
        "N4": (100.0, 100.0),
        "N5": (100.0, 100.0),
    }
    for nct_id, (treatment_n, comparator_n) in specs.items():
        rows.extend(
            [
                {
                    "nct_id": nct_id,
                    "ctgov_group_code": "OG000",
                    "group_family": "OG",
                    "group_suffix": "000",
                    "mapped_design_group_id": f"{nct_id}-A",
                    "mapped_arm_title": "LCZ696",
                    "mapped_group_type": "EXPERIMENTAL",
                    "mapped_intervention_names": "LCZ696",
                    "mapping_status": "mapped",
                    "mapping_method": "suffix_projection_from_anchor",
                    "mapping_confidence": "medium",
                    "anchor_group_family": "BG",
                    "anchor_ctgov_group_code": "BG000",
                    "anchor_count_value": treatment_n,
                },
                {
                    "nct_id": nct_id,
                    "ctgov_group_code": "OG001",
                    "group_family": "OG",
                    "group_suffix": "001",
                    "mapped_design_group_id": f"{nct_id}-B",
                    "mapped_arm_title": "Enalapril",
                    "mapped_group_type": "ACTIVE_COMPARATOR",
                    "mapped_intervention_names": "Enalapril",
                    "mapping_status": "mapped",
                    "mapping_method": "suffix_projection_from_anchor",
                    "mapping_confidence": "medium",
                    "anchor_group_family": "BG",
                    "anchor_ctgov_group_code": "BG001",
                    "anchor_count_value": comparator_n,
                },
            ]
        )
        if nct_id == "N5":
            rows.extend(
                [
                    {
                        "nct_id": nct_id,
                        "ctgov_group_code": "EG000",
                        "group_family": "EG",
                        "group_suffix": "000",
                        "mapped_design_group_id": f"{nct_id}-A",
                        "mapped_arm_title": "LCZ696",
                        "mapped_group_type": "EXPERIMENTAL",
                        "mapped_intervention_names": "LCZ696",
                        "mapping_status": "mapped",
                        "mapping_method": "suffix_projection_from_anchor",
                        "mapping_confidence": "medium",
                        "anchor_group_family": "BG",
                        "anchor_ctgov_group_code": "BG000",
                        "anchor_count_value": treatment_n,
                    },
                    {
                        "nct_id": nct_id,
                        "ctgov_group_code": "EG001",
                        "group_family": "EG",
                        "group_suffix": "001",
                        "mapped_design_group_id": f"{nct_id}-B",
                        "mapped_arm_title": "Enalapril",
                        "mapped_group_type": "ACTIVE_COMPARATOR",
                        "mapped_intervention_names": "Enalapril",
                        "mapping_status": "mapped",
                        "mapping_method": "suffix_projection_from_anchor",
                        "mapping_confidence": "medium",
                        "anchor_group_family": "BG",
                        "anchor_ctgov_group_code": "BG001",
                        "anchor_count_value": comparator_n,
                    },
                ]
            )
    return pd.DataFrame(rows)


def test_build_signed_effect_estimates_splits_surfaces_and_derives_precision() -> None:
    outcomes = build_outcomes_fixture()
    candidates = build_effect_candidates(outcomes)

    estimates = build_signed_effect_estimates(
        outcomes,
        candidates,
        build_arm_mapping_fixture(),
        topic=PHASE1_TOPIC,
    )

    assert len(estimates) == 6
    assert not estimates["surface_label"].str.startswith("Baseline").any()

    n1 = estimates.loc[estimates["nct_id"] == "N1"].iloc[0]
    assert n1["effect_measure"] == "mean_difference"
    assert isclose(float(n1["effect_value"]), 2.9, rel_tol=0.0, abs_tol=1e-6)
    assert isclose(float(n1["effect_precision"]), sqrt(2.15**2 + 2.0**2), rel_tol=0.0, abs_tol=1e-6)
    assert n1["precision_status"] == "reported_standard_error"

    week4 = estimates.loc[
        (estimates["nct_id"] == "N2") & (estimates["surface_label"] == "Week 4:")
    ].iloc[0]
    assert isclose(float(week4["effect_value"]), -0.5, rel_tol=0.0, abs_tol=1e-6)
    assert isclose(
        float(week4["effect_precision"]),
        sqrt((1.59**2 / 13.0) + (1.97**2 / 14.0)),
        rel_tol=0.0,
        abs_tol=1e-6,
    )
    assert week4["precision_status"] == "derived_from_standard_deviation_and_anchor_counts"

    n4 = estimates.loc[estimates["nct_id"] == "N4"].iloc[0]
    assert n4["effect_measure"] == "log_risk_ratio"
    assert isclose(float(n4["effect_value"]), log((15.0 / 100.0) / (8.0 / 100.0)), rel_tol=0.0, abs_tol=1e-6)
    assert isclose(
        float(n4["effect_precision"]),
        sqrt((1.0 / 15.0) - (1.0 / 100.0) + (1.0 / 8.0) - (1.0 / 100.0)),
        rel_tol=0.0,
        abs_tol=1e-6,
    )
    assert n4["derivation_method"] == "participant_partition_log_risk_ratio"

    n5 = estimates.loc[estimates["nct_id"] == "N5"].iloc[0]
    assert n5["effect_measure"] == "log_risk_ratio"
    assert isclose(float(n5["effect_value"]), log((2.0 / 100.0) / (6.0 / 100.0)), rel_tol=0.0, abs_tol=1e-6)
    assert isclose(
        float(n5["effect_precision"]),
        sqrt((1.0 / 2.0) - (1.0 / 100.0) + (1.0 / 6.0) - (1.0 / 100.0)),
        rel_tol=0.0,
        abs_tol=1e-6,
    )
    assert n5["derivation_method"] == "reported_event_log_risk_ratio"


def test_build_signed_effect_estimates_fail_closed_on_ambiguous_anchor_precision() -> None:
    outcomes = build_outcomes_fixture()
    candidates = build_effect_candidates(outcomes)

    estimates = build_signed_effect_estimates(
        outcomes,
        candidates,
        build_arm_mapping_fixture(),
        topic=PHASE1_TOPIC,
    )

    n3 = estimates.loc[estimates["nct_id"] == "N3"].iloc[0]
    assert n3["surface_label"] == "Change from BL at Week 12 (FAS with MI)"
    assert pd.isna(n3["effect_precision"])
    assert n3["precision_status"] == "ambiguous_population_for_anchor_counts"
    assert n3["estimand_type"] == "change_from_baseline"


def test_materialize_signed_effect_outputs_writes_artifacts(tmp_path: Path) -> None:
    output_dir = tmp_path / "outputs"
    output_dir.mkdir(parents=True)

    outcomes = build_outcomes_fixture()
    candidates = build_effect_candidates(outcomes)
    arm_mapping = build_arm_mapping_fixture()

    outcomes.to_parquet(output_dir / "trial_outcomes_long.parquet", index=False)
    candidates.to_parquet(output_dir / "effect_candidates.parquet", index=False)
    arm_mapping.to_parquet(output_dir / "arm_group_mapping.parquet", index=False)

    manifest = materialize_signed_effect_outputs(output_dir, topic=PHASE1_TOPIC)

    assert manifest["topic_slug"] == "sacubitril_valsartan_hfref"
    assert manifest["signed_effect_surface_count"] == 6
    assert manifest["signed_effect_candidate_count"] == 5
    assert manifest["precision_ready_surface_count"] == 5
    assert (output_dir / "signed_effect_estimates.parquet").exists()
    assert (output_dir / "signed_effect_trial_summary.parquet").exists()
    assert (output_dir / "signed_effect_report.md").exists()
    assert (output_dir / "signed_effect_manifest.json").exists()
