from __future__ import annotations

import pandas as pd

from trial_transportability_atlas.effect_candidates import build_effect_candidates


def test_build_effect_candidates_classifies_supported_and_unsupported_rows() -> None:
    frame = pd.DataFrame(
        [
            {
                "nct_id": "NCTA",
                "source_table": "outcome_measurements",
                "record_type": "measurement",
                "outcome_id": "1",
                "outcome_type": "PRIMARY",
                "outcome_name": "Walk distance",
                "analysis_population": "all",
                "time_frame": "12 weeks",
                "unit": "meters",
                "result_group_id": "10",
                "ctgov_group_code": "OG1",
                "classification": None,
                "category": None,
                "param_type": "MEAN",
                "value_text": "100",
                "value_num": 100.0,
                "dispersion_type": "Standard Deviation",
                "dispersion_value": "15",
                "event_type": None,
                "subjects_affected": None,
                "subjects_at_risk": None,
                "event_count": None,
                "organ_system": None,
                "adverse_event_term": None,
                "provenance": "x",
            },
            {
                "nct_id": "NCTA",
                "source_table": "outcome_measurements",
                "record_type": "measurement",
                "outcome_id": "1",
                "outcome_type": "PRIMARY",
                "outcome_name": "Walk distance",
                "analysis_population": "all",
                "time_frame": "12 weeks",
                "unit": "meters",
                "result_group_id": "11",
                "ctgov_group_code": "OG2",
                "classification": None,
                "category": None,
                "param_type": "MEAN",
                "value_text": "85",
                "value_num": 85.0,
                "dispersion_type": "Standard Deviation",
                "dispersion_value": "18",
                "event_type": None,
                "subjects_affected": None,
                "subjects_at_risk": None,
                "event_count": None,
                "organ_system": None,
                "adverse_event_term": None,
                "provenance": "x",
            },
            {
                "nct_id": "NCTB",
                "source_table": "reported_events",
                "record_type": "reported_event",
                "outcome_id": None,
                "outcome_type": None,
                "outcome_name": "Heart failure worsening",
                "analysis_population": None,
                "time_frame": "12 months",
                "unit": "participants",
                "result_group_id": "20",
                "ctgov_group_code": "OG1",
                "classification": None,
                "category": None,
                "param_type": None,
                "value_text": "4",
                "value_num": 4.0,
                "dispersion_type": None,
                "dispersion_value": None,
                "event_type": "serious",
                "subjects_affected": 2,
                "subjects_at_risk": 100,
                "event_count": 4,
                "organ_system": "Cardiac disorders",
                "adverse_event_term": "Heart failure worsening",
                "provenance": "y",
            },
            {
                "nct_id": "NCTB",
                "source_table": "reported_events",
                "record_type": "reported_event",
                "outcome_id": None,
                "outcome_type": None,
                "outcome_name": "Heart failure worsening",
                "analysis_population": None,
                "time_frame": "12 months",
                "unit": "participants",
                "result_group_id": "21",
                "ctgov_group_code": "OG2",
                "classification": None,
                "category": None,
                "param_type": None,
                "value_text": "8",
                "value_num": 8.0,
                "dispersion_type": None,
                "dispersion_value": None,
                "event_type": "serious",
                "subjects_affected": 6,
                "subjects_at_risk": 100,
                "event_count": 8,
                "organ_system": "Cardiac disorders",
                "adverse_event_term": "Heart failure worsening",
                "provenance": "y",
            },
            {
                "nct_id": "NCTC",
                "source_table": "outcome_measurements",
                "record_type": "measurement",
                "outcome_id": "9",
                "outcome_type": "SECONDARY",
                "outcome_name": "Biomarker median",
                "analysis_population": "all",
                "time_frame": "12 weeks",
                "unit": "pg/mL",
                "result_group_id": "30",
                "ctgov_group_code": "OG1",
                "classification": None,
                "category": None,
                "param_type": "MEDIAN",
                "value_text": "10",
                "value_num": 10.0,
                "dispersion_type": None,
                "dispersion_value": None,
                "event_type": None,
                "subjects_affected": None,
                "subjects_at_risk": None,
                "event_count": None,
                "organ_system": None,
                "adverse_event_term": None,
                "provenance": "z",
            },
            {
                "nct_id": "NCTC",
                "source_table": "outcome_measurements",
                "record_type": "measurement",
                "outcome_id": "9",
                "outcome_type": "SECONDARY",
                "outcome_name": "Biomarker median",
                "analysis_population": "all",
                "time_frame": "12 weeks",
                "unit": "pg/mL",
                "result_group_id": "31",
                "ctgov_group_code": "OG2",
                "classification": None,
                "category": None,
                "param_type": "MEDIAN",
                "value_text": "9",
                "value_num": 9.0,
                "dispersion_type": None,
                "dispersion_value": None,
                "event_type": None,
                "subjects_affected": None,
                "subjects_at_risk": None,
                "event_count": None,
                "organ_system": None,
                "adverse_event_term": None,
                "provenance": "z",
            },
        ]
    )

    candidates = build_effect_candidates(frame)

    assert len(candidates) == 3
    families = dict(zip(candidates["nct_id"], candidates["candidate_family"]))
    comparable = dict(zip(candidates["nct_id"], candidates["comparable_flag"]))
    reasons = dict(zip(candidates["nct_id"], candidates["comparability_reason"]))

    assert families["NCTA"] == "continuous_mean"
    assert comparable["NCTA"] is True
    assert families["NCTB"] == "binary_event_count"
    assert comparable["NCTB"] is True
    assert families["NCTC"] == "unsupported_median"
    assert comparable["NCTC"] is False
    assert reasons["NCTC"] == "unsupported_median"
